insert into reservations (name, email, phone, beach, rentalitem, rentaldate, createdAt)
values
("Ryan Tucker", "ryan@tucker.com", "7656022652", "Daytona Beach", "Chairs & Umbrella", "2018-12-04", current_timestamp()),
("Natalie Roberts", "natalie@roberts.com", "4075551212", "Cocoa Beach", "Chairs & Umbrella", "2018-12-04", current_timestamp()),
("Gabe Vermund", "gabe@vermund.com", "4075551234", "Siesta Key", "Chairs & Umbrella", "2018-12-04", current_timestamp()),
("Rick Compton", "rick@compton.com", "4075555678", "Key West", "Chairs & Umbrella", "2018-12-04", current_timestamp())


insert into inventory (beach, rentalitem, price, rentable, createdAt)
values
("Cocoa Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Cocoa Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Cocoa Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Cocoa Beach", "Chairs & Umbrella", 15.00, true,  current_timestamp()),
("Cocoa Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Daytona Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Daytona Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Daytona Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Daytona Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Daytona Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Destin", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Destin", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Destin", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Destin", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Destin", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Miami Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Miami Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Miami Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Miami Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Miami Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("New Smryna Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("New Smryna Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("New Smryna Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("New Smryna Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("New Smryna Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Panama City Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Panama City Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Panama City Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Panama City Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Panama City Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Pensacola Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Pensacola Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Pensacola Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Pensacola Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Pensacola Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Sanibel Island", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Sanibel Island", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Sanibel Island", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Sanibel Island", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Sanibel Island", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Siesta Key", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Siesta Key", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Siesta Key", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Siesta Key", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Siesta Key", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("St Augustine", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("St Augustine", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("St Augustine", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("St Augustine", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("St Augustine", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("St George Island", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("St George Island", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("St George Island", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("St George Island", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("St George Island", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("St Pete", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("St Pete", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("St Pete", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("St Pete", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("St Pete", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Vero Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Vero Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Vero Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Vero Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),
("Vero Beach", "Chairs & Umbrella", 15.00, true, current_timestamp()),



